import { useState, useRef, useCallback } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { getReport, type ReportResponse } from '../api/api'

const REPORT_TIMEOUT_MS = 120_000

export default function ReportViewer() {
  const [report, setReport] = useState<ReportResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [elapsed, setElapsed] = useState(0)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const abortRef = useRef<AbortController | null>(null)

  const startTimer = useCallback(() => {
    setElapsed(0)
    timerRef.current = setInterval(() => setElapsed((s) => s + 1), 1000)
  }, [])

  const stopTimer = useCallback(() => {
    if (timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }
  }, [])

  const fetchReport = async () => {
    setLoading(true)
    setError(null)
    setReport(null)
    startTimer()

    const controller = new AbortController()
    abortRef.current = controller
    const timeoutId = setTimeout(() => controller.abort(), REPORT_TIMEOUT_MS)

    try {
      const res = await fetch('http://localhost:8000/report', {
        signal: controller.signal,
      })
      clearTimeout(timeoutId)
      if (!res.ok) throw new Error(`Server returned ${res.status}`)
      const data = await res.json()
      setReport(data)
    } catch (e: unknown) {
      stopTimer()
      if (e instanceof DOMException && e.name === 'AbortError') {
        setError(`Report generation timed out after ${REPORT_TIMEOUT_MS / 1000}s. The backend may still be processing — try again in a moment.`)
      } else {
        console.error('[ReportViewer] fetch error:', e)
        setError(String(e))
      }
    } finally {
      clearTimeout(timeoutId)
      stopTimer()
      abortRef.current = null
      setLoading(false)
    }
  }

  const downloadReport = () => {
    if (!report) return
    const blob = new Blob([report.markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'cctv_investigation_report.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="max-w-4xl space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">Investigation Report</h1>
          <p className="text-slate-400 mt-1 text-sm">
            AI-generated summary of all CCTV events.
          </p>
        </div>
        <div className="flex gap-3">
          <button
            id="generate-report-btn"
            onClick={fetchReport}
            disabled={loading}
            className="btn-primary"
          >
            {loading ? (
              <><span className="spinner" /> Generating… {elapsed}s</>
            ) : (
              '⚡ Generate Report'
            )}
          </button>
          {report && (
            <button
              id="download-report-btn"
              onClick={downloadReport}
              className="btn-ghost"
            >
              ⬇ Download .md
            </button>
          )}
        </div>
      </div>

      {error && (
        <div className="card border-red-700/40 bg-red-950/30 text-red-300 text-sm flex items-start gap-2">
          <span className="text-lg leading-none mt-0.5">⚠</span>
          {error}
        </div>
      )}

      {!report && !loading && !error && (
        <div className="card flex flex-col items-center gap-4 py-24 text-center">
          <div className="w-16 h-16 rounded-2xl bg-indigo-600/20 border border-indigo-600/40 flex items-center justify-center text-3xl">
            📄
          </div>
          <div>
            <p className="text-slate-300 font-medium">No report generated yet</p>
            <p className="text-slate-500 text-sm mt-1">
              Click "Generate Report" to create an AI summary of all CCTV events.
            </p>
          </div>
        </div>
      )}

      {report && (
        <div id="report-content" className="card space-y-4">
          {/* Meta bar */}
          <div className="flex items-center justify-between border-b border-slate-800 pb-4">
            <div className="flex items-center gap-2">
              <span className="text-2xl">📋</span>
              <div>
                <p className="text-white font-semibold text-sm">CCTV Investigation Report</p>
                <p className="text-slate-500 text-xs">Generated by {report.provider_used}</p>
              </div>
            </div>
            <span className="badge bg-green-900/40 text-green-300">Ready</span>
          </div>

          {/* Markdown content */}
          <div className="report-prose">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {report.markdown}
            </ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  )
}
